server:
  port: 8880

spider:
  host: http://localhost
  port: 1024
  username:
  password:

tumblebug:
  host: http://localhost
  port: 1323
  username: default
  password: default

cost:
  estimation:
    updateInterval: "168h"

load:
  retry: 2
  timeout:
    monitoringAgentInstall: "7m"
    commandExecution: "50m"
    uninstallAgent: "7m"
  # 부하 발생 환경 구축에 사용할 리소스 이름 설정
  defaultResourceName:
    namespace: "ant-default-ns"     # 네임스페이스 이름
    mci: "ant-default-mci"         # MCI 이름
    vm: "ant-default-vm"           # VM 이름
    sshKey: "ant-default-shared"   # SSH 키 이름 (접미사는 자동 추가)
  jmeter:
    dir: "/opt/ant/jmeter"
    version: 5.6
  image:
    # CB-Tumblebug v0.11.8+ 스마트 매칭 기능 사용
    useSmartMatching: true
    
    # 안정성을 위한 하드코딩된 이미지만 사용 (프로덕션 환경 권장)
    useFallbackImagesOnly: false     # true: fallbackImages만 사용, false: 스마트 검색 사용
    
    preferredOs: "ubuntu 22.04"  # 선호하는 OS (스마트 매칭용)
    fallbackOs: "ubuntu 20.04"   # 대체 OS (스마트 매칭용)
    
    # 이미지 검색 옵션 (useFallbackImagesOnly: false일 때만 사용)
    searchOptions:
      isRegisteredByAsset: false      # Asset 등록 이미지만 검색 여부 (false: 모든 이미지)
      includeDeprecatedImage: false   # Deprecated 이미지 포함 여부
      includeBasicImageOnly: true     # Basic 이미지만 검색 (Ubuntu 지원)
      maxResults: 50                  # 최대 검색 결과 수 (충분한 선택지 확보)
    
    # OS별 검색 키워드 (스마트 매칭용)
    osKeywords:
      ubuntu: ["ubuntu", "canonical"]
      centos: ["centos", "rhel"]
      amazon: ["amazon", "amzn"]
    
    # 멀티 CSP 지원을 위한 폴백 이미지 설정 (스마트 매칭 실패 시 사용)
    fallbackImages:
      aws:
        "ap-northeast-1": "ami-0c3fd0f5d33134a76"  # Ubuntu 22.04 LTS (Tokyo)
        "ap-northeast-2": "ami-0f37ba4f1a9f199d1"  # Ubuntu 22.04 LTS (Seoul)
        "ap-southeast-1": "ami-0f37ba4f1a9f199d1"  # Ubuntu 22.04 LTS (Singapore)
        "us-east-1": "ami-0f37ba4f1a9f199d1"       # Ubuntu 22.04 LTS (US East)
        "us-west-2": "ami-0f37ba4f1a9f199d1"       # Ubuntu 22.04 LTS (US West)
      azure:
        "koreacentral": "Canonical:0001-com-ubuntu-server-jammy:22_04-lts-gen2:latest"
        "eastus": "Canonical:0001-com-ubuntu-server-jammy:22_04-lts-gen2:latest"
      gcp:
        "asia-northeast3": "ubuntu-2204-jammy-v20231213"
        "us-central1": "ubuntu-2204-jammy-v20231213"
      ncp:
        "KR": "SW.VSVR.OS.LNX64.UBNTU.SVR2004.LTS"
  spec:
    # VM 스펙 요구사항 (Load Generator용)
    # minVcpu: 2        # 최소 vCPU
    # maxVcpu: 8        # 최대 vCPU (기존 8에서 2로 변경)
    # minMemory: 4      # 최소 메모리 (GB)
    # maxMemory: 8      # 최대 메모리 (GB) (기존 8에서 4로 변경)
    minVcpu: 2        # 최소 vCPU (for medium)
    maxVcpu: 4        # 최대 vCPU
    minMemory: 4      # 최소 메모리 (GB)(for medium)
    maxMemory: 8      # 최대 메모리 (GB)
    # provider 제거 - 동적으로 기존 VM의 CSP 정보에서 추출
    # 아키텍처 제한: x86_64 (ARM64와 호환되지 않는 AMI 사용)
    architecture: "x86_64"  # x86_64 아키텍처 강제 사용

log:
  level: debug

database:
  driver: "postgres"
  host: "localhost"
  port: "5432"
  user: "cm-ant-user"
  password: "cm-ant-secret"
  name: "cm-ant-db"
