server:
  port: 8880

spider:
  host: http://localhost
  port: 1024
  username:
  password:

tumblebug:
  host: http://localhost
  port: 1323
  username: default
  password: default

cost:
  estimation:
    updateInterval: "168h"

load:
  retry: 2
  timeout:
    monitoringAgentInstall: "7m"
    commandExecution: "50m"
    uninstallAgent: "7m"
  # 부하 발생 환경 구축에 사용할 리소스 이름 설정
  defaultResourceName:
    namespace: "ant-default-ns"     # 네임스페이스 이름
    mci: "ant-default-mci"         # MCI 이름
    vm: "ant-default-vm"           # VM 이름
    sshKey: "ant-default-shared"   # SSH 키 이름 (접미사는 자동 추가)
  jmeter:
    dir: "/opt/ant/jmeter"
    version: 5.6
  image:
    # CB-Tumblebug v0.11.8+ 스마트 매칭 기능 사용
    useSmartMatching: true
    
    preferredOs: "ubuntu 22.04"  # 선호하는 OS (스마트 매칭용)
    fallbackOs: "ubuntu 20.04"   # 대체 OS (스마트 매칭용)
    
    # OS별 검색 키워드 (스마트 매칭용)
    osKeywords:
      ubuntu: ["ubuntu", "canonical"]
      centos: ["centos", "rhel"]
      amazon: ["amazon", "amzn"]
    
    # AWS 리전별 기본 이미지 목록 (스마트 매칭 실패 시 폴백용)
    awsImages:
      "ap-northeast-2": "ami-0f37ba4f1a9f199d1"  # Ubuntu 22.04 LTS (최신)
      "ap-southeast-1": "ami-0f37ba4f1a9f199d1"  # Ubuntu 22.04 LTS
      "us-east-1": "ami-0f37ba4f1a9f199d1"       # Ubuntu 22.04 LTS
      "us-west-2": "ami-0f37ba4f1a9f199d1"       # Ubuntu 22.04 LTS
  spec:
    # VM 스펙 요구사항 (Load Generator용)
    # minVcpu: 2        # 최소 vCPU
    # maxVcpu: 8        # 최대 vCPU (기존 8에서 2로 변경)
    # minMemory: 4      # 최소 메모리 (GB)
    # maxMemory: 8      # 최대 메모리 (GB) (기존 8에서 4로 변경)
    minVcpu: 1        # 최소 vCPU
    maxVcpu: 2        # 최대 vCPU (기존 8에서 2로 변경)
    minMemory: 1      # 최소 메모리 (GB)
    maxMemory: 4      # 최대 메모리 (GB) (기존 8에서 4로 변경)
    provider: "aws"   # 클라우드 프로바이더
    # 아키텍처 제한: x86_64 (ARM64와 호환되지 않는 AMI 사용)
    architecture: "x86_64"  # x86_64 아키텍처 강제 사용

log:
  level: debug

database:
  driver: "postgres"
  host: "localhost"
  port: "5432"
  user: "cm-ant-user"
  password: "cm-ant-secret"
  name: "cm-ant-db"
