// Code generated by swaggo/swag. DO NOT EDIT.

package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ant/api/v1/env": {
            "get": {
                "description": "Get all of the load test environments",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Load Test Environment]"
                ],
                "summary": "Get the list of load test environments",
                "operationId": "LoadEnvironments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.LoadEnvRes"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ant/api/v1/load/config": {
            "get": {
                "description": "Get all the load test execution configurations.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Load Test Configuration]"
                ],
                "summary": "Get all load execution config",
                "operationId": "LoadExecutionConfigs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.LoadExecutionRes"
                            }
                        }
                    },
                    "500": {
                        "description": "something went wrong.try again.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ant/api/v1/load/config/{loadTestKey}": {
            "get": {
                "description": "Get a load test execution config by load test key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Load Test Configuration]"
                ],
                "summary": "Get load execution config",
                "operationId": "LoadExecutionConfig",
                "parameters": [
                    {
                        "type": "string",
                        "description": "load test eky",
                        "name": "loadTestKey",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.LoadExecutionRes"
                        }
                    },
                    "500": {
                        "description": "something went wrong. try again.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ant/api/v1/load/result": {
            "get": {
                "description": "After start load test, get the result of load test.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Load Test Result]"
                ],
                "summary": "Get the result of single load test result",
                "operationId": "LoadTestResult",
                "parameters": [
                    {
                        "type": "string",
                        "description": "load test key",
                        "name": "loadTestKey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "format of load test result aggregate",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "loadTestKey must be passed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "sorry, internal server error while getting load test result;",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ant/api/v1/load/result/metrics": {
            "get": {
                "description": "Get the result of metrics for target server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Load Test Result]"
                ],
                "summary": "Get the result of single load test metrics",
                "operationId": "LoadTestMetrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "load test key",
                        "name": "loadTestKey",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "loadTestKey must be passed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "sorry, internal server error while getting load test result;",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ant/api/v1/load/start": {
            "post": {
                "description": "Start load test. Load Environment Id must be passed or Load Environment must be defined.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Load Test Execution]"
                ],
                "summary": "Start load test",
                "operationId": "StartLoadTest",
                "parameters": [
                    {
                        "description": "load test execution configuration request",
                        "name": "loadTestReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.LoadExecutionConfigReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "load test environment is not correct",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "sorry, internal server error while executing load test;",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ant/api/v1/load/state": {
            "get": {
                "description": "Get all the load test execution state.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Load Test State]"
                ],
                "summary": "Get all load execution state",
                "operationId": "LoadExecutionStates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.LoadExecutionStateRes"
                            }
                        }
                    },
                    "500": {
                        "description": "something went wrong.try again.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ant/api/v1/load/state/{loadTestKey}": {
            "get": {
                "description": "Get a load test execution state by load test key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Load Test State]"
                ],
                "summary": "Get load execution state",
                "operationId": "LoadExecutionState",
                "parameters": [
                    {
                        "type": "string",
                        "description": "load test key",
                        "name": "loadTestKey",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.LoadExecutionStateRes"
                        }
                    },
                    "500": {
                        "description": "something went wrong. try again.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ant/api/v1/load/stop": {
            "post": {
                "description": "After start load test, stop the load test by passing the load test key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Load Test Execution]"
                ],
                "summary": "Stop load test",
                "operationId": "StopLoadTest",
                "parameters": [
                    {
                        "description": "load test key",
                        "name": "loadTestKeyReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.LoadTestKeyReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "pass propertiesId if you want to stop test",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "sorry, internal server error while executing load test;",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ant/api/v1/load/tester": {
            "post": {
                "description": "Install load test tester in the delivered load test environment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Load Test Tester]"
                ],
                "summary": "Install load test tester",
                "operationId": "InstallLoadTester",
                "parameters": [
                    {
                        "description": "load test environment request",
                        "name": "loadEnvReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.LoadEnvReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "load test environment is not correct",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "sorry, internal server error while executing load test;",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ant/api/v1/load/tester/{envId}": {
            "delete": {
                "description": "Uninstall load test tester in the delivered load test environment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Load Test Tester]"
                ],
                "summary": "Uninstall load test tester",
                "operationId": "UninstallLoadTester",
                "parameters": [
                    {
                        "type": "string",
                        "description": "load test environment id",
                        "name": "envId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "pass me correct body;",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "something went wrong.try again.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/load/monitoring/agent/install": {
            "post": {
                "description": "Install a monitoring agent on specific MCIS.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MonitoringAgentManagement"
                ],
                "summary": "Install Metrics Monitoring Agent",
                "operationId": "InstallMonitoringAgent",
                "parameters": [
                    {
                        "description": "Monitoring Agent Installation Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.MonitoringAgentInstallationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully installed monitoring agent",
                        "schema": {
                            "$ref": "#/definitions/app.AntResponse-load_MonitoringAgentInstallationResult"
                        }
                    },
                    "400": {
                        "description": "Monitoring agent installation info is not correct.",
                        "schema": {
                            "$ref": "#/definitions/app.AntResponse-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.AntResponse-string"
                        }
                    }
                }
            }
        },
        "/api/v1/load/monitoring/agents": {
            "get": {
                "description": "Retrieve monitoring agent information based on specified criteria.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MonitoringAgentManagement"
                ],
                "summary": "Retrieve Monitoring Agent Information",
                "operationId": "GetAllMonitoringAgentInfos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace ID",
                        "name": "nsId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "MCIS ID",
                        "name": "mcisId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "VM ID",
                        "name": "vmId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results per page",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number for pagination",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved monitoring agent information",
                        "schema": {
                            "$ref": "#/definitions/app.AntResponse-load_GetAllMonitoringAgentInfoResult"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/app.AntResponse-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.AntResponse-string"
                        }
                    }
                }
            }
        },
        "/api/v1/load/monitoring/agents/uninstall": {
            "post": {
                "description": "Uninstall monitoring agents from specified VMs or all VMs in an MCIS.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MonitoringAgentManagement"
                ],
                "summary": "Uninstall Monitoring Agents",
                "operationId": "UninstallMonitoringAgent",
                "parameters": [
                    {
                        "description": "Monitoring Agent Uninstallation Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.MonitoringAgentInstallationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Number of affected results",
                        "schema": {
                            "$ref": "#/definitions/app.AntResponse-int64"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/app.AntResponse-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.AntResponse-string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.LoadEnvReq": {
            "type": "object",
            "properties": {
                "installLocation": {
                    "$ref": "#/definitions/constant.InstallLocation"
                },
                "mcisId": {
                    "type": "string"
                },
                "nsId": {
                    "type": "string"
                },
                "pemKeyPath": {
                    "type": "string"
                },
                "publicIp": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "vmId": {
                    "type": "string"
                }
            }
        },
        "api.LoadEnvRes": {
            "type": "object",
            "properties": {
                "installLocation": {
                    "$ref": "#/definitions/constant.InstallLocation"
                },
                "loadEnvId": {
                    "type": "integer"
                },
                "mcisId": {
                    "type": "string"
                },
                "nsId": {
                    "type": "string"
                },
                "pemKeyPath": {
                    "type": "string"
                },
                "publicIp": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "vmId": {
                    "type": "string"
                }
            }
        },
        "api.LoadExecutionConfigReq": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "string"
                },
                "envId": {
                    "type": "string"
                },
                "httpReqs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.LoadExecutionHttpReq"
                    }
                },
                "loadEnvReq": {
                    "$ref": "#/definitions/api.LoadEnvReq"
                },
                "loadTestKey": {
                    "type": "string"
                },
                "rampUpSteps": {
                    "type": "string"
                },
                "rampUpTime": {
                    "type": "string"
                },
                "testName": {
                    "type": "string"
                },
                "virtualUsers": {
                    "type": "string"
                }
            }
        },
        "api.LoadExecutionHttpReq": {
            "type": "object",
            "properties": {
                "bodyData": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                }
            }
        },
        "api.LoadExecutionHttpRes": {
            "type": "object",
            "properties": {
                "bodyData": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "loadExecutionHttpId": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                }
            }
        },
        "api.LoadExecutionRes": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "string"
                },
                "loadEnv": {
                    "$ref": "#/definitions/api.LoadEnvRes"
                },
                "loadExecutionConfigId": {
                    "type": "integer"
                },
                "loadExecutionHttp": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.LoadExecutionHttpRes"
                    }
                },
                "loadExecutionState": {
                    "$ref": "#/definitions/api.LoadExecutionStateRes"
                },
                "loadTestKey": {
                    "type": "string"
                },
                "rampUpSteps": {
                    "type": "string"
                },
                "rampUpTime": {
                    "type": "string"
                },
                "testName": {
                    "type": "string"
                },
                "virtualUsers": {
                    "type": "string"
                }
            }
        },
        "api.LoadExecutionStateRes": {
            "type": "object",
            "properties": {
                "endAt": {
                    "type": "string"
                },
                "executionStatus": {
                    "$ref": "#/definitions/constant.ExecutionStatus"
                },
                "loadExecutionStateId": {
                    "type": "integer"
                },
                "loadTestKey": {
                    "type": "string"
                },
                "startAt": {
                    "type": "string"
                },
                "totalSec": {
                    "type": "integer"
                }
            }
        },
        "api.LoadTestKeyReq": {
            "type": "object",
            "properties": {
                "loadTestKey": {
                    "type": "string"
                }
            }
        },
        "app.AntResponse-int64": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "errorMessage": {
                    "type": "string"
                },
                "result": {
                    "type": "integer"
                },
                "successMessage": {
                    "type": "string"
                }
            }
        },
        "app.AntResponse-load_GetAllMonitoringAgentInfoResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "errorMessage": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/load.GetAllMonitoringAgentInfoResult"
                },
                "successMessage": {
                    "type": "string"
                }
            }
        },
        "app.AntResponse-load_MonitoringAgentInstallationResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "errorMessage": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/load.MonitoringAgentInstallationResult"
                },
                "successMessage": {
                    "type": "string"
                }
            }
        },
        "app.AntResponse-string": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "errorMessage": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "successMessage": {
                    "type": "string"
                }
            }
        },
        "app.MonitoringAgentInstallationReq": {
            "type": "object",
            "properties": {
                "mcisId": {
                    "type": "string"
                },
                "nsId": {
                    "type": "string"
                },
                "vmIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "constant.ExecutionStatus": {
            "type": "string",
            "enum": [
                "processing",
                "fetching",
                "success",
                "failed"
            ],
            "x-enum-varnames": [
                "Processing",
                "Fetching",
                "Success",
                "Failed"
            ]
        },
        "constant.InstallLocation": {
            "type": "string",
            "enum": [
                "local",
                "remote"
            ],
            "x-enum-varnames": [
                "Local",
                "Remote"
            ]
        },
        "load.GetAllMonitoringAgentInfoResult": {
            "type": "object",
            "properties": {
                "monitoringAgentInfos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/load.MonitoringAgentInstallationResult"
                    }
                },
                "totalRow": {
                    "type": "integer"
                }
            }
        },
        "load.MonitoringAgentInstallationResult": {
            "type": "object",
            "properties": {
                "agentType": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mcisId": {
                    "type": "string"
                },
                "nsId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "vmCount": {
                    "type": "integer"
                },
                "vmId": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
